apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      restartPolicy: Always
      containers:
        - name: node-backend
          image: coffeeinacafe/mediconnect-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "db-service"  # Same service name used for MySQL
            - name: DB_USER
              value: "testuser"
            - name: DB_PWD
              value: "rootroot"
            - name: MYSQL_DATABASE
              value: "mediconnect"
            - name: DB_PORT
              value: "3306"
            # - name: LOGGING_HOST
            #   value: "logstash"  # Assumes a logstash service exists
            # - name: LOGGING_PORT
            #   value: "5000"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
