apiVersion: v1
kind: Pod
metadata:
  name: backend-mysql-pod
  labels:
    app: backend-mysql
spec:
  containers:
    - name: mysql
      image: mysql:8
      imagePullPolicy: IfNotPresent
      args: ["--port=3306"]
      resources:
        requests:
          memory: "2Gi"
          cpu: "2500m"
        limits:
          memory: "5Gi"
          cpu: "5000m"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootroot"
        - name: MYSQL_USER
          value: "testuser"
        - name: MYSQL_PASSWORD
          value: "rootroot"
        - name: MYSQL_DATABASE
          value: "mediconnect"
        - name: MYSQL_ROOT_HOST
          value: "%"
        - name: MYSQL_TCP_PORT
          value: "3306"

    - name: node-backend
      image: coffeeinacafe/mediconnect-backend:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      resources:
        requests:
          memory: "2Gi"
          cpu: "2500m"
        limits:
          memory: "5Gi"
          cpu: "5000m"
      env:
        - name: DB_HOST
          value: "127.0.0.1"       # Communicate via localhost inside the pod
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "testuser"
        - name: DB_PWD
          value: "rootroot"
        - name: MYSQL_DATABASE
          value: "mediconnect"

  volumes:
    - name: mysql-data
      emptyDir: {}
