apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  serviceName: "db-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:8
          imagePullPolicy: IfNotPresent
          args: ["--port=3300"]
          ports:
            - containerPort: 3300
          env:
            - name: MYSQL_TCP_PORT
              value: "3300"
            - name: MYSQL_ROOT_PASSWORD
              value: "rootroot"
            - name: MYSQL_USER
              value: "testuser"
            - name: MYSQL_PASSWORD
              value: "rootroot"
            - name: MYSQL_DATABASE
              value: "mediconnect"
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3300
      targetPort: 3300
  type: ClusterIP
---
