---
# Pull Docker images manually
- name: Pull mysql:8 image
  command: docker pull mysql:8

- name: Pull Docker images
  command: docker pull {{ docker_user }}/{{ item }}
  loop:
    - mediconnect-webrtc_server:latest
    - mediconnect-frontend:latest
    - mediconnect-backend:latest
#   register: pull_result

# - name: Show image pull results
#   debug:
#     msg: "Pulled image {{ item.item }} with result: {{ item.stdout }}"
#   loop: "{{ pull_result.results }}"