- name: Spin up application at remote machine
  hosts: all
  # become: true
  remote_user: deepanshpandey
  environment:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  vars_files:
    - my_vault.yml
  vars:
    docker_user: coffeeinacafe
  roles:
    - pull-docker-images
    # - deploy-combined_backend
    - deploy-database
    - wait
    - deploy-backend
    - wait
    - deploy-frontend
    - wait
    - deploy-WebRTC_Signaling_Server
    - deploy-port_forwarding
    # - deploy-logging