- name: Reset Kubernetes resources on remote machine
  hosts: all
  remote_user: deepanshpandey
  tasks:
    - name: Delete all Kubernetes resources
      shell: |
        kubectl delete all --all
        kubectl delete pvc --all
        kubectl delete hpa --all
        pkill -f "kubectl port-forward"