- name: Reset Kubernetes resources on remote machine
  hosts: all
  become: true
  become_user: root
  gather_facts: false
  remote_user: deepanshpandey
  tasks:
    - name: Delete all Kubernetes resources
      shell: |
        kubectl delete all --all
        kubectl delete pvc --all
        kubectl delete hpa --all
        sudo pkill -f "kubectl port-forward"