services:
  # MySQL
  db:
    container_name: mysql-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootroot'
      MYSQL_DATABASE: 'mediconnect'
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: testuser
    volumes:
      - db-data:/var/lib/mysql

  # Angular Frontend
  frontend:
    container_name: frontend
    restart: always
    build: ./Frontend/
    ports:
      - "8000:80"
    depends_on:
      - backend
      - webrtc_server

  # Node.js Backend
  backend:
    container_name: backend
    restart: always
    build: ./Backend/
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PWD: rootroot
      MYSQL_DB: mediconnect
    depends_on:
      - db

  # WebRTC Signaling Server
  webrtc_server:
    container_name: webrtc_server
    restart: always
    build: ./WebRTC_Signaling_Server/
    ports:
      - "4440:4440"

volumes:
  db-data: