version: '3.1'

services:
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootroot'
      MYSQL_ROOT_HOST: '%'
      # MYSQL_DATABASE: 'app'
      # MYSQL_USER: 'user'
      # MYSQL_PASSWORD: 'rootroot'
    # ports: 
    #   - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

 
 
  frontend:
    container_name: frontend
    restart: always
    build: ./Ng-frontend/
    ports: 
      - "4200:80"
    depends_on: 
      - backend
      - webrtc_server
 
  backend:
    container_name: backend
    restart: always
    build: ./Backend/
    ports: 
      - "3000:3000"
    depends_on: 
      - db
  
  webrtc_server:
    container_name: webrtc_server
    restart: always
    build: ./WebRTC_Signaling_Server/
    ports: 
      - "4440:4440"


volumes:
  db-data: