version: '3.1'

services:

  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootroot'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql
      
  frontend:
    container_name: frontend
    image: coffeeinacafe/mediconnect_frontend
    restart: always
    ports: 
      - "4200:80"
    depends_on: 
      - backend
      - webrtc_server

  backend:
    container_name: backend
    image: coffeeinacafe/mediconnect_backend 
    restart: always
    ports: 
      - "3000:3000"
    depends_on: 
      - db
  
  webrtc_server:
    container_name: webrtc_server
    image: coffeeinacafe/mediconnect_webrtc_server
    restart: always
    ports: 
      - "4440:4440"

volumes:
  db-data:


