apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: frontend-web
          image: coffeeinacafe/mediconnect-frontend:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          ports:
            - containerPort: 4200 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web-service
spec:
  selector:
    app: frontend-web
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30004
  type: NodePort
