apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: frontend-web
          image: coffeeinacafe/mediconnect-frontend:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "2000m"
              memory: "2Gi"
            limits:
              cpu: "5000m"
              memory: "4Gi"
          ports:
            - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web-service
spec:
  selector:
    app: frontend-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
