- name: Port-forward backend
  shell: nohup kubectl port-forward service/node-backend-service 3000:3000 > /tmp/backend.log 2>&1 &
  async: 1
  poll: 0

- name: Port-forward frontend
  shell: nohup kubectl port-forward service/frontend-web-service 8000:80 > /tmp/frontend.log 2>&1 &
  async: 1
  poll: 0

- name: Port-forward signaling server
  shell: nohup kubectl port-forward service/webrtc-server-service 4440:4440 > /tmp/signaling.log 2>&1 &
  async: 1
  poll: 0

- name: Port-forward MYSQL
  shell: nohup kubectl port-forward service/db-service 3300:3300 > /tmp/mysql.log 2>&1 &
  async: 1
  poll: 0

#   # This is for the logging application
# - name: port-forward for logstash
#   command: kubectl port-forward service/logstash-service 5000:5000
# - name: port-forward for backend logging
#   command: kubectl port-forward service/node-backend-service 5000:5000
# - name: port-forward for logstash monitoring
#   command: kubectl port-forward service/logstash-monitoring-service 9600:9600
# - name: port-forward for elasticsearch
#   command: kubectl port-forward service/elasticsearch-service 9200:9200
# - name: port-forward for kibana
#   command: kubectl port-forward service/kibana-service 5601:5601