- name: port-forward for backend
  command: kubectl port-forward service/node-backend-service 3000:3000
- name: port-forward for frontend
  command: kubectl port-forward service/frontend-web-service 80:80
- name: port-forward for signaling server
  command: kubectl port-forward service/webrtc-server-service 4440:4440

#   # This is for the logging application
# - name: port-forward for logstash
#   command: kubectl port-forward service/logstash-service 5000:5000
# - name: port-forward for backend logging
#   command: kubectl port-forward service/node-backend-service 5000:5000
# - name: port-forward for logstash monitoring
#   command: kubectl port-forward service/logstash-monitoring-service 9600:9600
# - name: port-forward for elasticsearch
#   command: kubectl port-forward service/elasticsearch-service 9200:9200
# - name: port-forward for kibana
#   command: kubectl port-forward service/kibana-service 5601:5601